deploy:
  services:
    - name: snuba-api
      healthcheck: sleep 10 && curl -I '127.0.0.1:11218/health?thorough=true'
      chef_roles:
        - snuba-api
    - name: snuba-consumer
      percent: 1.0
      chef_roles:
        - snuba-consumer
    - name: snuba-replacer
      percent: 1.0
      chef_roles:
        - snuba-consumer
