# wake up travis
sudo: required
dist: trusty
language: python
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E0C56BD4    # optional
  - sudo apt-add-repository "deb http://repo.yandex.ru/clickhouse/deb/stable/ main/"
  - sudo apt-get -qq update
  - sudo apt-get install clickhouse-server-common clickhouse-client -y
  - sudo service clickhouse-server start
  - pip install -r requirements.txt
  - python setup.py develop
script:
  - py.test -s
